# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20180729_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='actual_design',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='actual_development',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='actual_testing',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='estimated_design',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='estimated_development',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='estimated_testing',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='title',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='delivery date'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.CharField(default=None, max_length=128, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='shipping date'),
        ),
    ]
