# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20180729_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_no',
            field=models.CharField(default=None, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
