# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_tracking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('S', 'Shipped'), ('I', 'In Transit'), ('D', 'Delivered')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected delivery date'),
        ),
    ]
