# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20180729_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='company',
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.Company'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shipments.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
