# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20180730_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(blank=True, choices=[('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=20, null=True),
        ),
    ]
