# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_auto_20180730_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='product',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Product'),
        ),
    ]
